# Theme template paths. These must be modified appropriately.
themeTemplate  = "../rsc/themeTemplate.html"
searchTemplate = "../rsc/searchTemplate.html"
itemTemplate   = "../rsc/itemTemplate.html"
include_path   = "../rsc/include"

# Change which tags godir will look for. If you're using a pre-made theme, leave these at their defaults.
tag_contents      = "$content$"
tag_file_href     = "$file-href$"
tag_item_type     = "$item-type$"
tag_root_step     = "$root-step$"
tag_domain        = "$domain$"
tag_root_dir      = "$root-dir$"
tag_sidenav       = "$sidenav$"
tag_breadcrumb    = "$breadcrumb$"
tag_filename      = "$filename$"
tag_last_modified = "$last-modified$"
tag_filesize      = "$filesize$"
tag_title         = "$title$"

# Should godir follow symlinks? This may cause security issues.
follow_symlinks = false

# These files will be completely ignored by godir.
# The defaults include godir-generated files and directories and should probably not be touched.
use_regex = true # Set to false to disable regex parsing on excludes.

# These default excludes probably shouldn't be touched unless you know what you're doing.
excludes = [
    "rsc",
    ".git",
    "include",
    "index.html",
    "search.html",
    ".gdx",
]

domain = "localhost" # Set this to your domain name.
title  = "My Title" # Set this to the title you want to appear in your website.
